### ISSUE TITLE
为什么会找不到这个模块的属性，明明已经引入？

### ISSUE THREAD

**Issue by liuronghu** [Roujack/mathAI#10]
Traceback (most recent call last):
  File "e:\python_project\mathai-master\mainai\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\python_project\mathai-master\mainai\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\python_project\mathai-master\mainai\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\python_project\mathai-master\mainai\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "e:\python_project\mathai-master\mainai\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\python_project\mathai-master\mainai\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\python_project\mathAI-master\mainai\welcome.py", line 49, in upload_file
    result_file = solver.solve(save_file_path)
  File "E:\python_project\mathAI-master\mainai\solver\__init__.py", line 68, in solve
    node_list = parser.characters_to_nodes(characters)
AttributeError: module 'parser' has no attribute 'characters_to_nodes'

**Comment by Roujack** [comment]
https://github.com/Roujack/mathAI/issues/5

**Comment by liuronghu** [comment]
C:\Users\Administrator>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import parser
>>>    测试了一下，原来已经跟系统模块冲突了

**Comment by liuronghu** [comment]
感谢回答！！！！

**Comment by Roujack** [comment]
也许我得改一下parser模块的名字，不然很多人又会遇到这个问题。
