### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by IMINIming** [Roujack/mathAI#12]
你好，我在求数的“平方根”时会报如下错误：
Traceback (most recent call last):
  File "E:/AI_exercise/mathAI/系统代码(code)/test.py", line 3, in <module>
    save_filename = solver.solve('./testImgs/easy sqrt/61.jpg')
  File "E:\AI_exercise\mathAI\系统代码(code)\solver\__init__.py", line 70, in solve
    post_order(parser_tree)
  File "E:\AI_exercise\mathAI\系统代码(code)\calculator\__init__.py", line 278, in post_order
    t = post_order(child[0])
  File "E:\AI_exercise\mathAI\系统代码(code)\calculator\__init__.py", line 202, in post_order
    node['status'] = child[0]['status']
KeyError: 'status'
请问时什么原因，应该怎么修改？

**Comment by tellw** [comment]
同，应该是模型处理的问题。

**Comment by Roujack** [comment]
我现在公开的模型只有加减乘除这种比较简单的功能，没有开放求平方根的代码。
