### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by NicholasIrving** [Roujack/mathAI#13]
按照文档配置好之后，127.0.0.1:5000 能进入，但是点击upload的时候显示内部服务器错误
错误信息如下：
WARNING: Logging before flag parsing goes to stderr.
W0704 22:22:49.066677 14804 deprecation_wrapper.py:119] From C:\Users\Nicho\Desktop\master\mathAI-master\系统代码(code)\tools\cnn_model.py:9: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0704 22:22:49.066677 14804 deprecation_wrapper.py:119] From C:\Users\Nicho\Desktop\master\mathAI-master\系统代码(code)\tools\cnn_model.py:9: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

I0704 22:22:49.067677 14804 estimator.py:1790] Using default config.
I0704 22:22:49.067677 14804 estimator.py:209] Using config: {'_model_dir': './my_cnn_model_config5', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000002574B928BA8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

**Comment by Roujack** [comment]
这个看报错信息是tf的版本问题，你看看这个提示：The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.？

**Comment by NicholasIrving** [comment]
我发现，就算没有打开项目，也没有runserver，什么都不做的情况下在浏览器输入127.0.0.1:5000还是能进入主页的，我觉得应该是这里的问题。

**Comment by NicholasIrving** [comment]
他后续报了AttributeError: module 'parser' has no attribute 'characters_to_nodes'错误，我把全部parser换成parser1的时候能运行，不过只有加法和减法能够正确识别和计算，其他的次方什么的就只识别出一个数字了，输出的latex有问题，像：
![image](https://user-images.githubusercontent.com/22784080/60798611-0f9a7500-a1a4-11e9-9aa0-c8b8dcd625ba.png)
![image](https://user-images.githubusercontent.com/22784080/60798641-217c1800-a1a4-11e9-88bf-df9ee9c1128f.png)

是半开源的问题呢还是哪里的问题？

**Comment by Roujack** [comment]
半开源的问题

**Comment by ligowi** [comment]
你好 我想问一下
 WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:33: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.max_pooling2d instead.
WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:62: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:66: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
2019-11-01 16:00:52.952759: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./my_cnn_model_config5\model.ckpt-16000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow\python\training\monitored_session.py:809: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Traceback (most recent call last):
  File "E:/Pythoncode/math/main.py", line 68, in <module>
    node_list=parser.characters_to_nodes(sorted_characters)
AttributeError: module 'parser' has no attribute 'characters_to_nodes'
最后一行这个AttributeError是怎么解决的呢

**Comment by Roujack** [comment]
> 你好 我想问一下
> WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.**init** (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> To construct input pipelines, use the `tf.data` module.
> WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> To construct input pipelines, use the `tf.data` module.
> INFO:tensorflow:Calling model_fn.
> WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.conv2d instead.
> WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:33: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.max_pooling2d instead.
> WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:62: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.dense instead.
> WARNING:tensorflow:From E:\Pythoncode\math\tools\cnn_model.py:66: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.dropout instead.
> INFO:tensorflow:Done calling model_fn.
> INFO:tensorflow:Graph was finalized.
> 2019-11-01 16:00:52.952759: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use standard file APIs to check for files with this prefix.
> INFO:tensorflow:Restoring parameters from ./my_cnn_model_config5\model.ckpt-16000
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> WARNING:tensorflow:From E:\Pythoncode\math\venv\lib\site-packages\tensorflow\python\training\monitored_session.py:809: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> To construct input pipelines, use the `tf.data` module.
> Traceback (most recent call last):
> File "E:/Pythoncode/math/main.py", line 68, in
> node_list=parser.characters_to_nodes(sorted_characters)
> AttributeError: module 'parser' has no attribute 'characters_to_nodes'
> 最后一行这个AttributeError是怎么解决的呢

https://github.com/Roujack/mathAI/issues/5
