### ISSUE TITLE
test.py 运行，在执行  img_preprocess.py 中报错 

### ISSUE THREAD

**Issue by alen19082062** [Roujack/mathAI#14]
错误描述：

在 pycharm 中运行 test.py  ，报错 ，信息如下：

Traceback (most recent call last):
  File "F:/git_code/ai/mathAI/系统代码(code)/test.py", line 3, in <module>
    save_filename = solver.solve('./testImgs/easy +/1.jpg')
  File "F:\git_code\ai\mathAI\系统代码(code)\solver\__init__.py", line 20, in solve
    symbols = binary_img_segment(binary_img, original_img)
  File "F:\git_code\ai\mathAI\系统代码(code)\tools\img_preprocess.py", line 66, in binary_img_segment
    img, contours, hierarchy = cv2.findContours(binary_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)#cv2.RETR_TREE
ValueError: not enough values to unpack (expected 3, got 2) 

我的运行环境 
py 3.7.3 
cv 4.1.0
tensorflow 2.0.0beta1 

是不是因为环境不一样导致的呢  
请您帮忙看一下

**Comment by alen19082062** [comment]
与版本有关，把 opencv 的版本降到 3 ，解决了这个问题 
pip install opencv-python==3.4.3.18 

版本 4   cv2.findContours() 返回 2 个参数 ，版本3 返回 3 个参数  
参考这个文章 
https://www.cnblogs.com/guobin-/p/10842486.html
