### ISSUE TITLE
while clicking upload button getting the below error

### ISSUE THREAD

**Issue by Jeeth-rathore** [Roujack/mathAI#18]
[2020-07-01 14:43:17,926] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Users/jeethusingh/PycharmProjects/aiMath/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeethusingh/PycharmProjects/aiMath/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeethusingh/PycharmProjects/aiMath/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeethusingh/PycharmProjects/aiMath/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jeethusingh/PycharmProjects/aiMath/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeethusingh/PycharmProjects/aiMath/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeethusingh/PycharmProjects/aiMath/welcome.py", line 41, in upload_file
    result_file = solver.solve(save_file_path)
  File "/Users/jeethusingh/PycharmProjects/aiMath/solver/__init__.py", line 73, in solve
    if parser_tree['status'] == STATUS['solved']:
KeyError: 'status'
127.0.0.1 - - [01/Jul/2020 14:43:17] "POST / HTTP/1.1" 500 -

**Comment by Roujack** [comment]
sorry for the error and late reply. I guest the main reason is the input is too complicate to recognize. The published system only support add/sub/mul/div operator.  Other kind of expression can not be calculated. Could you upload the image you input?

**Comment by Jeeth-rathore** [comment]
![3](https://user-images.githubusercontent.com/65868201/86464291-ce07c000-bd4c-11ea-9035-c827779acb0d.jpg)

**Comment by Jeeth-rathore** [comment]
Thank you for your response.....i have tried giving the above image.....apart from add/sub/mul/div ..can weperform other operations as well using your code?

**Comment by Roujack** [comment]
Sorry, the sqrt operator is not support. (not implement in my code) For strong math expression recognization system, please refer to TAP(Track, Attend and predict) model.
